### PR TITLE
Update testing and clean up deprecation warning

### PR DESCRIPTION
**Pull request by shortdudey123**

### CODE REVIEW

**Comment by shortdudey123** [comment]
@mburns @xamebax thoughts?

**Comment by mburns** [comment]
Looks good to me. 👍

**Comment by shortdudey123** [comment]
@mburns cool!  let me know if anything comes up, otherwise i will assume you will merge this

**Comment by shortdudey123** [comment]
@mburns any updates on your side?

**Comment by mburns** [comment]
This got lost in the shuffle. Still looks good. Let's merge!

**Comment by shortdudey123** [comment]
Awesome, thanks!!

**Pull request merged**
