### PR TITLE
Make host file idempotent.

### PR DESCRIPTION
**Pull request by danieljimenez**

### CODE REVIEW

**Comment by gsdevme** [comment]
Whats the status of this?

**Comment by danieljimenez** [comment]
I've been using it for months off my fork with no issue.

**Comment by gsdevme** [comment]
Has the maintainer given up? This PR is 6months old. Im also wanting to remove the deprecated warnings but I will just fork if thats no chance of a merged PR.

**Comment by danieljimenez** [comment]
Probably, I see that a lot with Chef Cookbooks. You're welcome to submit a PR to my fork and maybe we can make that the new one going forward? Useful cookbook.

**Comment by gsdevme** [comment]
Yeah I've forked many chef cookbooks, supermarket is full of dead cookbooks. very sad

**Comment by gsdevme** [comment]
I will investigate this cookbook, its another fork but much more upto date https://github.com/nathantsoi/chef-cookbook-hostname

**Comment by gsdevme** [comment]
https://supermarket.chef.io/cookbooks/hostnames

**Comment by flaccid** [comment]
system cookbook still going strong :)

**Comment by gsdevme** [comment]
https://supermarket.chef.io/cookbooks/system 
!!! I hadn't seen this

**Comment by mburns** [comment]
👍

**Pull request merged**
